apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: counting-db
  description: counting service database
  tags:
    - mongodb
    - database
spec:
  type: database
  lifecycle: experimental
  owner: group:guests
  system: counting-app